name: Run

on: 
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          docker run atdr.meo.ws/archiveteam/imgur-grab --concurrent 1 Hans5958
        timeout-minutes: 60
        continue-on-error: true
